package core.grammar.french;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import core.grammar.Word;

class TestFrench {

	French f = new French();
	String s1 = "bonjour";
	String s2 = "int�ressement";
	String s3 = "caract�re";
	String s4 = "r�guli�rement";
	String s5 = "cr�ation";
	String s6 = "l'am�ne";
	String s7 = "l'arm�e";
	String s8 = "l'�cran";
	String s9 = "l'identit�";
	String s10 = "s'�carter";
	String s11 = "l�";
	String s12 = "m�dico-professionnelles";
	String s13 = "�";
	String s14 = "correspondanci�res";
	String s15 = "d�n�";
	String s16 = "surd�velopp�es";
	String s17 = "radiom�tallographie";
	String s18 = "exsud�rent";
	String s19 = "d�";
	String s20 = "d�parasitassions";
	String s21 = "go�";
	String s22 = "arri�re-grand-tantes";
	String s23 = "m�";
	String s24 = "d�cl�ricaliserions";
	String s25 = "contre-r�volutionnaire";
	String s26 = "courrou�assions";
	String s27 = "d�chromeront";
	String s28 = "m�dico-p�dagogiques";
	String s29 = "�ta";
	String s30 = "interchangeabilit�";
	String s31 = "controvers�t";
	String s32 = "f�d�raliseraient";
	String s33 = "tch�coslovaques";
	String s34 = "botanis�";
	String s35 = "pagnot�rent";
	String s36 = "rinc�s";
	String s37 = "ins�r�t";
	String s38 = "d�senflassions";
	String s39 = "d�sembourgeois�rent";
	String s40 = "compr�hensibilit�s";
	String s41 = "d�christianisassions";
	String s42 = "d�sapprovisionnassiez";
	String s43 = "s�l�nographiques";
	String s44 = "neutralis�";
	String s45 = "substantialit�s";
	String s46 = "institutionnalis�rent";
	String s47 = "�gravillonnasses";
	String s48 = "d�personnaliserait";
	String s49 = "interf�rom�tre";
	String s50 = "radiot�l�graphiassent";
	String s51 = "Rajeun�t";
	String s52 = "N�v�";
	String s53 = "d�Clarai";
	String s54 = "�viderA";
	String s55 = "Recouch�s";
	String s56 = "b�illerAs";
	String s57 = "d�cOngelaSsions";
	String s58 = "z�OlitEs";
	String s59 = "d�ratis�rent";
	String s60 = "exprim�es";
	String s61 = "c�Toyai";
	String s62 = "pr�Toriale";
	String s63 = "couiLLonn�es";
	String s64 = "�picURismes";
	String s65 = "imag�rENt";
	String s66 = "pr��mINent";
	String s67 = "rECevabilit�";
	String s68 = "d�tAXerez";
	String s69 = "d�safFIlieriez";
	String s70 = "coNF�r�mES";
	String s71 = "�pURements";
	String s72 = "rEPA�t";
	String s73 = "r�chAPPons";
	String s74 = "cern�ES";
	String s75 = "hame�ONNions";
	String s76 = "hav�MEs";
	String s77 = "pr�VINssent";
	String s78 = "plaISant�s";
	String s79 = "d�sensibILIs�t";
	String s80 = "FESs�s";
	String s81 = "RADIOdiffus�es";
	String s82 = "d�CAPElait";
	String s83 = "d�sint�GRAI";
	String s84 = "r�ESSAYEriez";
	String s85 = "aCIDit�s";
	String s86 = "d�sH�riterions";
	String s87 = "h�berGERIons";
	String s88 = "d�COMPRimerions";
	String s89 = "fr�LANT";
	String s90 = "d�SANNex�";
	String s91 = "d�LUT�e";
	String s92 = "ALAMbiqu�mes";
	String s93 = "piERR�tes";
	String s94 = "pr�VENTif";
	String s95 = "r�TRIbutions";
	String s96 = "�PINciez";
	String s97 = "d�LIN�eriez";
	String s98 = "agit�ES";
	String s99 = "d�VALErions";
	String s100 = "r�TROc�D�reNT";

	@Test
	void testMatchWord() {
		assertEquals("bonjour", f.matchWordWithDictionnary(new Word(s1)).getTheWord());
		assertEquals("intéressement", f.matchWordWithDictionnary(new Word(s2)).getTheWord());
		assertEquals("caractère", f.matchWordWithDictionnary(new Word(s3)).getTheWord());
		assertEquals("régulièrement", f.matchWordWithDictionnary(new Word(s4)).getTheWord());
		assertEquals("création", f.matchWordWithDictionnary(new Word(s5)).getTheWord());
		assertEquals("l'amène", f.matchWordWithDictionnary(new Word(s6)).getTheWord());
		assertEquals("l'armée", f.matchWordWithDictionnary(new Word(s7)).getTheWord());
		assertEquals("l'écran", f.matchWordWithDictionnary(new Word(s8)).getTheWord());
		assertEquals("l'identité", f.matchWordWithDictionnary(new Word(s9)).getTheWord());
		assertEquals("s'écarter", f.matchWordWithDictionnary(new Word(s10)).getTheWord());
		assertEquals("là", f.matchWordWithDictionnary(new Word(s11)).getTheWord());
		assertEquals("médico-professionnelles", f.matchWordWithDictionnary(new Word(s12)).getTheWord());
		assertEquals("à", f.matchWordWithDictionnary(new Word(s13)).getTheWord());
		assertEquals("correspondancières", f.matchWordWithDictionnary(new Word(s14)).getTheWord());
		assertEquals("dîné", f.matchWordWithDictionnary(new Word(s15)).getTheWord());
		assertEquals("surdéveloppées", f.matchWordWithDictionnary(new Word(s16)).getTheWord());
		assertEquals("radiométallographie", f.matchWordWithDictionnary(new Word(s17)).getTheWord());
		assertEquals("exsudèrent", f.matchWordWithDictionnary(new Word(s18)).getTheWord());
		assertEquals("dé", f.matchWordWithDictionnary(new Word(s19)).getTheWord());
		assertEquals("déparasitassions", f.matchWordWithDictionnary(new Word(s20)).getTheWord());
		assertEquals("goï", f.matchWordWithDictionnary(new Word(s21)).getTheWord());
		assertEquals("arrière-grand-tantes", f.matchWordWithDictionnary(new Word(s22)).getTheWord());
		assertEquals("mû", f.matchWordWithDictionnary(new Word(s23)).getTheWord());
		assertEquals("décléricaliserions", f.matchWordWithDictionnary(new Word(s24)).getTheWord());
		assertEquals("contre-révolutionnaire", f.matchWordWithDictionnary(new Word(s25)).getTheWord());
		assertEquals("courrouçassions", f.matchWordWithDictionnary(new Word(s26)).getTheWord());
		assertEquals("déchromeront", f.matchWordWithDictionnary(new Word(s27)).getTheWord());
		assertEquals("médico-pédagogiques", f.matchWordWithDictionnary(new Word(s28)).getTheWord());
		assertEquals("ôta", f.matchWordWithDictionnary(new Word(s29)).getTheWord());
		assertEquals("interchangeabilité", f.matchWordWithDictionnary(new Word(s30)).getTheWord());
		assertEquals("controversât", f.matchWordWithDictionnary(new Word(s31)).getTheWord());
		assertEquals("fédéraliseraient", f.matchWordWithDictionnary(new Word(s32)).getTheWord());
		assertEquals("tchécoslovaques", f.matchWordWithDictionnary(new Word(s33)).getTheWord());
		assertEquals("botanisé", f.matchWordWithDictionnary(new Word(s34)).getTheWord());
		assertEquals("pagnotèrent", f.matchWordWithDictionnary(new Word(s35)).getTheWord());
		assertEquals("rincés", f.matchWordWithDictionnary(new Word(s36)).getTheWord());
		assertEquals("insérât", f.matchWordWithDictionnary(new Word(s37)).getTheWord());
		assertEquals("désenflassions", f.matchWordWithDictionnary(new Word(s38)).getTheWord());
		assertEquals("désembourgeoisèrent", f.matchWordWithDictionnary(new Word(s39)).getTheWord());
		assertEquals("compréhensibilités", f.matchWordWithDictionnary(new Word(s40)).getTheWord());
		assertEquals("déchristianisassions", f.matchWordWithDictionnary(new Word(s41)).getTheWord());
		assertEquals("désapprovisionnassiez", f.matchWordWithDictionnary(new Word(s42)).getTheWord());
		assertEquals("sélénographiques", f.matchWordWithDictionnary(new Word(s43)).getTheWord());
		assertEquals("neutralisé", f.matchWordWithDictionnary(new Word(s44)).getTheWord());
		assertEquals("substantialités", f.matchWordWithDictionnary(new Word(s45)).getTheWord());
		assertEquals("institutionnalisèrent", f.matchWordWithDictionnary(new Word(s46)).getTheWord());
		assertEquals("égravillonnasses", f.matchWordWithDictionnary(new Word(s47)).getTheWord());
		assertEquals("dépersonnaliserait", f.matchWordWithDictionnary(new Word(s48)).getTheWord());
		assertEquals("interféromètre", f.matchWordWithDictionnary(new Word(s49)).getTheWord());
		assertEquals("radiotélégraphiassent", f.matchWordWithDictionnary(new Word(s50)).getTheWord());
		assertEquals("Rajeunît", f.matchWordWithDictionnary(new Word(s51)).getTheWord());
		assertEquals("Névé", f.matchWordWithDictionnary(new Word(s52)).getTheWord());
		assertEquals("déClarai", f.matchWordWithDictionnary(new Word(s53)).getTheWord());
		assertEquals("éviderA", f.matchWordWithDictionnary(new Word(s54)).getTheWord());
		assertEquals("Recouchés", f.matchWordWithDictionnary(new Word(s55)).getTheWord());
		assertEquals("bâillerAs", f.matchWordWithDictionnary(new Word(s56)).getTheWord());
		assertEquals("décOngelaSsions", f.matchWordWithDictionnary(new Word(s57)).getTheWord());
		assertEquals("zéOlitEs", f.matchWordWithDictionnary(new Word(s58)).getTheWord());
		assertEquals("dératisèrent", f.matchWordWithDictionnary(new Word(s59)).getTheWord());
		assertEquals("exprimées", f.matchWordWithDictionnary(new Word(s60)).getTheWord());
		assertEquals("côToyai", f.matchWordWithDictionnary(new Word(s61)).getTheWord());
		assertEquals("préToriale", f.matchWordWithDictionnary(new Word(s62)).getTheWord());
		assertEquals("couiLLonnées", f.matchWordWithDictionnary(new Word(s63)).getTheWord());
		assertEquals("épicURismes", f.matchWordWithDictionnary(new Word(s64)).getTheWord());
		assertEquals("imagèrENt", f.matchWordWithDictionnary(new Word(s65)).getTheWord());
		assertEquals("préémINent", f.matchWordWithDictionnary(new Word(s66)).getTheWord());
		assertEquals("rECevabilité", f.matchWordWithDictionnary(new Word(s67)).getTheWord());
		assertEquals("détAXerez", f.matchWordWithDictionnary(new Word(s68)).getTheWord());
		assertEquals("désafFIlieriez", f.matchWordWithDictionnary(new Word(s69)).getTheWord());
		assertEquals("coNFérâmES", f.matchWordWithDictionnary(new Word(s70)).getTheWord());
		assertEquals("épURements", f.matchWordWithDictionnary(new Word(s71)).getTheWord());
		assertEquals("rEPAît", f.matchWordWithDictionnary(new Word(s72)).getTheWord());
		assertEquals("réchAPPons", f.matchWordWithDictionnary(new Word(s73)).getTheWord());
		assertEquals("cernéES", f.matchWordWithDictionnary(new Word(s74)).getTheWord());
		assertEquals("hameçONNions", f.matchWordWithDictionnary(new Word(s75)).getTheWord());
		assertEquals("havâMEs", f.matchWordWithDictionnary(new Word(s76)).getTheWord());
		assertEquals("préVINssent", f.matchWordWithDictionnary(new Word(s77)).getTheWord());
		assertEquals("plaISantés", f.matchWordWithDictionnary(new Word(s78)).getTheWord());
		assertEquals("désensibILIsât", f.matchWordWithDictionnary(new Word(s79)).getTheWord());
		assertEquals("FESsés", f.matchWordWithDictionnary(new Word(s80)).getTheWord());
		assertEquals("RADIOdiffusées", f.matchWordWithDictionnary(new Word(s81)).getTheWord());
		assertEquals("déCAPElait", f.matchWordWithDictionnary(new Word(s82)).getTheWord());
		assertEquals("désintéGRAI", f.matchWordWithDictionnary(new Word(s83)).getTheWord());
		assertEquals("réESSAYEriez", f.matchWordWithDictionnary(new Word(s84)).getTheWord());
		assertEquals("aCIDités", f.matchWordWithDictionnary(new Word(s85)).getTheWord());
		assertEquals("désHériterions", f.matchWordWithDictionnary(new Word(s86)).getTheWord());
		assertEquals("héberGERIons", f.matchWordWithDictionnary(new Word(s87)).getTheWord());
		assertEquals("déCOMPRimerions", f.matchWordWithDictionnary(new Word(s88)).getTheWord());
		assertEquals("frôLANT", f.matchWordWithDictionnary(new Word(s89)).getTheWord());
		assertEquals("déSANNexé", f.matchWordWithDictionnary(new Word(s90)).getTheWord());
		assertEquals("déLUTée", f.matchWordWithDictionnary(new Word(s91)).getTheWord());
		assertEquals("ALAMbiquâmes", f.matchWordWithDictionnary(new Word(s92)).getTheWord());
		assertEquals("piERRâtes", f.matchWordWithDictionnary(new Word(s93)).getTheWord());
		assertEquals("préVENTif", f.matchWordWithDictionnary(new Word(s94)).getTheWord());
		assertEquals("réTRIbutions", f.matchWordWithDictionnary(new Word(s95)).getTheWord());
		assertEquals("éPINciez", f.matchWordWithDictionnary(new Word(s96)).getTheWord());
		assertEquals("déLINéeriez", f.matchWordWithDictionnary(new Word(s97)).getTheWord());
		assertEquals("agitéES", f.matchWordWithDictionnary(new Word(s98)).getTheWord());
		assertEquals("déVALErions", f.matchWordWithDictionnary(new Word(s99)).getTheWord());
		assertEquals("réTROcéDèreNT", f.matchWordWithDictionnary(new Word(s100)).getTheWord());
	}
}
